# Default language if you have a multi-language setup
DefaultContentLanguage = "en"

baseURL = "https://example.com"

theme = "amperage"

pygmentsUseClasses = true

# Number of posts shown per page (dafault: 10)
paginate = 5

# Language sections
[languages]
    [languages.en]
        contentDir = "content/en"
        languageName = "English"
        languageCode = "en"
        title = "Amperage theme!"
        description = "This is an demo for the Amperage theme!"
        weight = 1
    [languages.pl]
        contentDir = "content/pl"
        languageName = "Polish"
        languageCode = "pl"
        title = "Amperage theme!"
        description = "To jest demo dla Amperage theme!"
        weight = 1
        [[languages.pl.menu.main]]
            identifier = "home"
            name = "Strona główna"
            url = "/pl/"
            weight = 7
        [[languages.pl.menu.main]]
            identifier = "post"
            name = "Posty"
            url = "/pl/post/"
            weight = 8
        [[languages.pl.menu.main]]
            identifier = "offers"
            name = "Oferty"
            url = "/pl/offer/"
            weight = 9
        [[languages.pl.menu.main]]
            identifier = "about-us"
            name = "O nas"
            url = "/pl/about-us/"
            weight = 10

# Menu elements
[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 7
[[menu.main]]
    identifier = "post"
    name = "Posts"
    url = "/post/"
    weight = 8
[[menu.main]]
    identifier = "offers"
    name = "Offers"
    url = "/offer/"
    weight = 9
[[menu.main]]
    identifier = "about-us"
    name = "About Us"
    url = "/about-us/"
    weight = 10


# Enable only tags taxonomy
[taxonomies]
    tag = "tags"

[params]
    copyright = "Amperage" # Name shown on footer copyright
    themeColor = "#333" # Theme color displayed on mobile browsers

    # Default AMP components for the whole site
    ampElements = ["amp-iframe", "amp-analytics", "amp-social-share", "amp-install-serviceworker"]

    # Google Analytics code
    # googleAnalytics = "UA-xxxxxxxxx-x"

    # Adsense publisher code
    # adsensePublisher = "ca-pub-123456789"

    # Comments Iframe URL
    # commentsEmbedUrl = "https://comments.example.com"

    # Social sites for metatags
    facebookSite = "example"
    twitterSite = "@example"

    # Structured data elements
    socialProfiles = ["https://twitter.com/example","https://www.linkedin.com/in/example/","https://github.com/example"]

    alternatePageName = "Amperage example"
    organizationLogo = "/logo.png"
    organizationName = "Asur"

    publisherName = "amperage"
    publisherLogo = "/logo-amp-article.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60

[outputs]
    home = [ "HTML", "RSS", "SearchIndex"]

[outputFormats]
    [outputFormats.SearchIndex]
        mediaType= "application/json"
        baseName= "search"
        isPlainText= true
        notAlternative= true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true